# Generated by Django 3.0.8 on 2020-10-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/no_image_ugzyyo.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
